package crocalert.app.ui.cameras

internal object CamerasMockData {
    val cameras: List<CameraUiItem> = listOf(
        CameraUiItem(
            id = "cam-12",
            name = "CAM-12 Delta",
            isActive = true,
            status = CameraStatus.Alert,
            lastCapture = "hace 2 días",
            imagesSent = 0,
            imagesExpected = 35,
            captureCount = 18,
            captureExpected = 24,
            missingCaptures = 6,
            integrityFlags = 2,
        ),
        CameraUiItem(
            id = "cam-04",
            name = "CAM-04 Curva del río",
            isActive = true,
            status = CameraStatus.Attention,
            lastCapture = "22:55",
            imagesSent = 26,
            imagesExpected = 35,
            captureCount = 26,
            captureExpected = 30,
            missingCaptures = 2,
            integrityFlags = 0,
        ),
        CameraUiItem(
            id = "cam-08",
            name = "CAM-08 Norte",
            isActive = true,
            status = CameraStatus.Attention,
            lastCapture = "20:05",
            imagesSent = 25,
            imagesExpected = 35,
            captureCount = 25,
            captureExpected = 30,
            missingCaptures = 3,
            integrityFlags = 1,
        ),
        CameraUiItem(
            id = "cam-01",
            name = "CAM-01 Bridge",
            isActive = true,
            status = CameraStatus.Ok,
            lastCapture = "23:55",
            imagesSent = 35,
            imagesExpected = 35,
            captureCount = 35,
            captureExpected = 35,
            missingCaptures = 0,
            integrityFlags = 0,
        ),
        CameraUiItem(
            id = "cam-03",
            name = "CAM-03 Eastern Gate",
            isActive = true,
            status = CameraStatus.Ok,
            lastCapture = "23:45",
            imagesSent = 34,
            imagesExpected = 35,
            captureCount = 34,
            captureExpected = 35,
            missingCaptures = 1,
            integrityFlags = 0,
        ),
        CameraUiItem(
            id = "cam-05",
            name = "CAM-05 North Trail",
            isActive = true,
            status = CameraStatus.Ok,
            lastCapture = "23:30",
            imagesSent = 35,
            imagesExpected = 35,
            captureCount = 35,
            captureExpected = 35,
            missingCaptures = 0,
            integrityFlags = 0,
        ),
        CameraUiItem(
            id = "cam-07",
            name = "CAM-07 Waterfall",
            isActive = true,
            status = CameraStatus.Ok,
            lastCapture = "22:15",
            imagesSent = 33,
            imagesExpected = 35,
            captureCount = 33,
            captureExpected = 35,
            missingCaptures = 2,
            integrityFlags = 0,
        ),
        CameraUiItem(
            id = "cam-09",
            name = "CAM-09 Riverside",
            isActive = true,
            status = CameraStatus.Ok,
            lastCapture = "23:00",
            imagesSent = 35,
            imagesExpected = 35,
            captureCount = 35,
            captureExpected = 35,
            missingCaptures = 0,
            integrityFlags = 0,
        ),
    )
}
